<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_...                                 _38e30b</name>
   <tag></tag>
   <elementGuidId>2205d840-fe5e-4f52-a93b-fb9e47615ec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='inputState'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputState</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Province</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              เลือกจังหวัด...


               กรุงเทพมหานคร 
               กระบี่ 
               กาญจนบุรี 
               กาฬสินธุ์ 
               กำแพงเพชร 
               ขอนแก่น  
               จันทบุรี 
               ฉะเชิงเทรา 
               ชลบุรี 
               ชัยนาท 
               ชัยภูมิ 
               ชุมพร 
               เชียงราย 
               เชียงใหม่ 
               ตรัง 
               ตราด 
               ตาก 
               นครนายก 
               นครปฐม 
               นครพนม 
               นครราชสีมา 
               นครศรีธรรมราช 
               นครสวรรค์ 
               นนทบุรี 
               นราธิวาส 
               น่าน 
               บึงกาฬ 
               บุรีรัมย์ 
               ปทุมธานี 
               ประจวบคีรีขันธ์ 
               ปราจีนบุรี 
               ปัตตานี 
               พระนครศรีอยุธยา 
               พังงา 
               พัทลุง 
               พิจิตร 
               พิษณุโลก 
               เพชรบุรี 
               เพชรบูรณ์ 
               แพร่ 
               พะเยา 
               ภูเก็ต 
               มหาสารคาม 
               มุกดาหาร 
               แม่ฮ่องสอน 
               ยะลา  
               ยโสธร 
               ร้อยเอ็ด 
               ระนอง 
               ระยอง  
               ราชบุรี 
               ลพบุรี 
               ลำปาง 
               ลำพูน 
               เลย 
               ศรีสะเกษ 
               สกลนคร 
               สงขลา 
               สตูล 
               สมุทรปราการ 
               สมุทรสงคราม 
               สมุทรสาคร 
               สระแก้ว 
               สระบุรี 
               สิงห์บุรี 
               สุโขทัย 
               สุพรรณบุรี 
               สุราษฎร์ธานี 
               สุรินทร์ 
               หนองคาย 
               หนองบัวลำภู 
               อ่างทอง 
               อุดรธานี 
               อุทัยธานี 
               อุตรดิตถ์  
               อุบลราชธานี 
               อำนาจเจริญ 


            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/from[1]/div[@class=&quot;container&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-md-2&quot;]/select[@id=&quot;inputState&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='inputState'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เลือกจังหวัด'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address (ที่อยู่)'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อำเภอ'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสไปรษณีย์'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
